apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: {{.Values.namespace}}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.16.1
        name: nginx
        envFrom:
        - configMapRef:
            name: {{.Values.ConfigMapName}}
        - secretRef:
            name: {{.Values.secretName}}
