apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: {{.Values.namespace}}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: 313422618945.dkr.ecr.eu-central-1.amazonaws.com/lirigzon:dev
        name: nextjs
        envFrom:
        - configMapRef:
            name: {{.Values.ConfigMapName}}
        - secretRef:
            name: {{.Values.secretName}}
