apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
   name: alb-ingress
   namespace: {{.Values.namespace}}
   annotations: 
    alb.ingress.kubernetes.io/target-type: 'ip'
    alb.ingress.kubernetes.io/group.name: common-alb
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
   ingressClassName: alb
   rules:
   - host: lirigzon.appstellar.com
     http:
       paths:
       - path: /
         pathType: Prefix
         backend:
           service:
             name: my-service
             port:
               number: {{.Values.portNumber}}