apiVersion: v1
kind: Pod
metadata:
  name: nginx-postgres
  namespace: nginx-ns
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
      - configMapRef:
          name: game-demo
    ports:
    - containerPort: 80
    volumeMounts:
      - name: configmap-as-volume
        mountPath: /home
  volumes:
    - name: configmap-as-volume
      configMap:
        name: game-demo
        items:
            - key: DB_HOSTNAME
              path: myconfigmapmount
            
         
         
